:url-proj: https://github.com/ccfontes/faas-bb
:img-ci-tests-status: {url-proj}/actions/workflows/faas_fn_build_invoke.yml/badge.svg
:img-ci-hadolint-status: {url-proj}/actions/workflows/hadolint.yml/badge.svg
:img-ci-clj-kondo-status: {url-proj}/actions/workflows/clj-kondo.yml/badge.svg
:img-ci-lychee-link-check-status: {url-proj}/actions/workflows/broken-link-checker.yml/badge.svg
:url-ci-status-tests: "{url-proj}/actions/workflows/faas_fn_build_invoke.yml"
:url-ci-status-hadolint: "{url-proj}/actions/workflows/hadolint.yml"
:url-ci-status-clj-kondo: "{url-proj}/actions/workflows/clj-kondo.yml"
:url-ci-status-lychee-link: "{url-proj}/actions/workflows/broken-link-checker.yml"
:img-license: https://img.shields.io/badge/license-MIT-black.svg

= faas-bb image:{img-ci-tests-status}[link={url-ci-status-tests}] image:{img-ci-hadolint-status}[link={url-ci-status-hadolint}] image:{img-ci-clj-kondo-status}[link={url-ci-status-clj-kondo}] image:{img-ci-lychee-link-check-status}[link={url-ci-status-lychee-link}] image:{img-license}[link=LICENSE]

An https://github.com/openfaas[OpenFaaS] template for writing Functions in https://github.com/babashka/babashka[Babashka].

== Prerequisites

* https://docs.openfaas.com/cli/install/[OpenFaaS CLI]: makes the `faas` command available.

== Usage

=== Pull OpenFaaS template

To create Babashka Functions with this template, use the following command *once*:
[source, bash]
----
faas template pull https://github.com/ccfontes/faas-bb
----
If you ever need to update the template, simply run the command above with the `--overwrite` flag.

=== Create a Babashka Function

Two languages are supported: `bb` (HTTP mode) and `bb-streaming`.

Create Babashka Functions as with the following command example:
[source, bash]
----
faas new --lang bb my-bb-function
----
`of-watchdog` mode here is HTTP. A new project is created for a function defined as `my-bb-function`. It will contain:

* a `function.handler` namespace that is required for the template to work properly. The requirement for this namespace is to have a top-level function defined as `handler`.
* a `bb.edn` file specifying classpath to find `function.handler`.

Although the Function namespace is called `function.handler`, the files themselves can be named anything you want. Example:
[source, yml]
----
my-function:
  handler: ./anything/my-function
  ...
----

=== Defining Function handler

In `bb` language:
[source, clojure]
----
(defn handler [{:keys [headers body context] :as event}] ...)
----
The `event` is a map containing the request `:headers`, `:body` and `:context` keys.

`context` contains a map of environment variables.

The `:headers` key contains headers, as such:
[source, clojure]
----
{:content-type "application/json"}
----

The `:env` map contains a map with the environment variables. Additional environment variables can be defined in the `stack.yml` file, as such:
[source, yml]
----
my-function:
  lang: bb
  handler: ./anything/my-function
  image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/my-function
  environment:
    MY_ENV1: foo
    MY_ENV2: 2
----
The `:env` key will contain:
[source, clojure]
----
 {:my-env1 "foo"
  :my-env2 2}
----

There are cases where string keys are preferable in the payload body, and it's possible to support them by setting `keywords: false` in the Function in `stack.yml`:
[source, yml]
----
my-function:
  lang: bb
  handler: ./anything/my-function
  image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/my-function
  environment:
    keywords: false
----

In `bb-streaming` language:
[source, clojure]
----
(defn handler [event] ...)
----
The `event` is the payload body.


== link:examples[Function examples]

See the link:examples[examples] directory to find a fully working set of OpenFaaS Functions written in Babashka.

== Tests

=== CI tests

All tests run in CI with Github Actions. Some commands link:.github/workflows/faas_fn_build_invoke.yml[can be found in a Github Actions workflow] to help you with testing your changes before pushing them to a topic branch.

=== Unit tests

Run locally the unit tests for `bb` language:
[source, bash]
----
cd template/bb
bb tests.clj
----
`tests.clj` is included with the template so you can test any changes you make to the template before using it.

== Contributing

Contributions are welcome! If you find a bug or have an idea for a new feature, please open an issue or submit a pull request.

The template may benefit from some common middleware functions, such as those offered in the https://github.com/ring-clojure/ring-defaults/blob/master/src/ring/middleware/defaults.clj[ring-defaults library]. Users are welcome to recommend integrating any middleware they think would be useful for handling common web application needs.

== Third party code

The following files are derived from https://github.com/ring-clojure[ring] to work with Babashka, originally authored by James Reeves and contributors, and used under the MIT license:

- link:template/bb/ring/middleware/json.clj[ring.middleware.json]
- link:template/bb/ring/util/io.clj[ring.util.io]
- link:template/bb/ring/util/mime_type.clj[ring.util.mime-type]
- link:template/bb/ring/util/parsing.clj[ring.util.parsing]
- link:template/bb/ring/util/response.clj[ring.util.response]
- link:template/bb/ring/util/time.clj[ring.util.time]

== link:LICENSE[License]

Copyright (c) 2023 Carlos da Cunha Fontes.

This project is licensed under the MIT License. See link:LICENSE[LICENSE] for details.
