:url-proj: https://github.com/ccfontes/faas-bb
:img-ci-tests-status: {url-proj}/actions/workflows/faas_fn_build_invoke.yml/badge.svg
:img-ci-hadolint-status: {url-proj}/actions/workflows/hadolint.yml/badge.svg
:img-ci-clj-kondo-status: {url-proj}/actions/workflows/clj-kondo.yml/badge.svg
:img-ci-lychee-link-check-status: {url-proj}/actions/workflows/broken-link-checker.yml/badge.svg
:url-ci-status-tests: "{url-proj}/actions/workflows/faas_fn_build_invoke.yml"
:url-ci-status-hadolint: "{url-proj}/actions/workflows/hadolint.yml"
:url-ci-status-clj-kondo: "{url-proj}/actions/workflows/clj-kondo.yml"
:url-ci-status-lychee-link: "{url-proj}/actions/workflows/broken-link-checker.yml"
:img-license: https://img.shields.io/badge/license-MIT-black.svg

= faas-bb image:{img-ci-tests-status}[link={url-ci-status-tests}] image:{img-ci-hadolint-status}[link={url-ci-status-hadolint}] image:{img-ci-clj-kondo-status}[link={url-ci-status-clj-kondo}] image:{img-ci-lychee-link-check-status}[link={url-ci-status-lychee-link}] image:{img-license}[link=LICENSE]

An https://github.com/openfaas[OpenFaaS] template for writing Functions in https://github.com/babashka/babashka[Babashka].

== Prerequisites

* https://docs.openfaas.com/cli/install/[OpenFaaS CLI]: makes the `faas` command available.

== Usage

=== Pull OpenFaaS template

To create Babashka Functions with this template, use the following command *once*:
[source, bash]
----
faas template pull https://github.com/ccfontes/faas-bb
----
If you ever need to update the template, simply run the command above with the `--overwrite` flag.

=== Create a Babashka Function

Two languages are supported: `bb` (HTTP mode) and `bb-streaming`.

Create Babashka Functions as with the following command example:
[source, bash]
----
faas new --lang bb my-bb-function
----
`of-watchdog` mode here is HTTP. A new project is created for a function defined as `my-bb-function`. It will contain:

* a `function.handler` namespace that is required for the template to work properly. The requirement for this namespace is to have a top-level function defined as `handler`.
* a `bb.edn` file specifying classpath to find `function.handler`.
* a `test` directory containing:
** a `run-tests.clj` script that runs the tests. You can use any test library and test runner you like.
** a `bb.edn` with `:paths` and `:deps` required to run the tests.

Although the Function namespace is called `function.handler`, the directory path to the Function handler can be named anything you want. Example:
[source, yml]
----
my-function:
  handler: ./anything/you-want
  ...
----

=== Defining Function handler

In `bb` language:
[source, clojure]
----
(defn handler [{:keys [headers body context] :as event}]
  ...)
----
`event` is a map containing `:headers`, `:body` and `:context` keys.

`:headers` contains headers, as such:
[source, clojure]
----
{:content-type "application/json"}
----

`:body` is the payload body. When passing a JSON object payload and using `bb` language, the payload will be automatically parsed as a Clojure map with keyword keys. There are cases where it's preferable to have string keys in the payload body, and it's possible to support them by setting `keywords: false` in the Function in `stack.yml`:
[source, yml]
----
my-function:
  lang: bb
  handler: ./anything/my-function
  image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/my-function
  environment:
    keywords: false
----

`:context` contains environment variables. Additional environment variables can be defined in the `stack.yml` file, as such:
[source, yml]
----
my-function:
  lang: bb
  handler: ./anything/my-function
  image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/my-function
  environment:
    MY_ENV1: foo
    MY_ENV2: 2
----
`:context` will contain:
[source, clojure]
----
 {:my-env1 "foo"
  :my-env2 2}
----

In `bb-streaming` language:
[source, clojure]
----
(defn handler [event] ...)
----
The `event` is extracted from the HTTP payload body, and the function return is used as the HTTP payload body for the response.

=== Adding namespaces

Namespace for each babashka source file created side by side with `handler.clj` must also be prefixed with `function.` Example: when creating a `view.clj` file in the same directory as `handler.clj`, namespace is `function.view`.

=== Function tests

To test the code of a Function, create a `test` directory in the Function's top-level directory, containing:

* `run-tests.clj`: A script that runs the tests. You can use any test library and test runner you like.
* `bb.edn`: with `{:paths ["../.."]}`

To disable running existing tests, set the `TEST` build time argument to `false`:
[source, yml]
----
my-function:
  lang: bb
  handler: ./anything/my-function
  image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/my-function
   build_args:
      TEST: false
----

== link:examples[Function examples]

See the link:examples[examples] directory to find a fully working set of OpenFaaS Functions written in Babashka.

== faas-bb tests

=== CI tests

All tests run in CI with Github Actions. Some commands link:.github/workflows/faas_fn_build_invoke.yml[can be found in a Github Actions workflow] to help you with testing your changes before pushing them to a topic branch.

=== Unit tests

Run locally the unit tests for the `bb` template.

The requirement is that babashka (`bb`) is https://github.com/babashka/babashka#installation[installed].

[source, bash]
----
cd template/bb
bb --config tests.edn tests.clj
----
`tests.clj` is included with the template so you can test any changes you make to the template before using it.

== Contributing

Contributions are welcome! If you find a bug or have an idea for a new feature, please open an issue or submit a pull request.

The template may benefit from some common middleware functions, such as those offered in the https://github.com/ring-clojure/ring-defaults/blob/master/src/ring/middleware/defaults.clj[ring-defaults library]. Users are welcome to recommend integrating any middleware they think would be useful for handling common web application needs.

== Third party code

The following files are derived from https://github.com/ring-clojure[ring] to work with Babashka, originally authored by James Reeves and contributors, and used under the MIT license:

* link:template/bb/lib/ring/middleware/json.clj[ring.middleware.json]
* link:template/bb/lib/ring/util/io.clj[ring.util.io]
* link:template/bb/lib/ring/util/mime_type.clj[ring.util.mime-type]
* link:template/bb/lib/ring/util/parsing.clj[ring.util.parsing]
* link:template/bb/lib/ring/util/response.clj[ring.util.response]
* link:template/bb/lib/ring/util/time.clj[ring.util.time]

== link:LICENSE[License]

Copyright (c) 2023 Carlos da Cunha Fontes.

This project is licensed under the MIT License. See link:LICENSE[LICENSE] for details.
