= OpenFaaS Functions in Babashka =

Go into the link:http[http] and link:streaming[streaming] directories to find the Babashka Function code examples.

The following documentation explains how to run these Functions in OpenFaaS.

See https://docs.openfaas.com/tutorials/first-python-function/[OpenFaaS website] for more detailed and up to date documentation.

== Prerequisites ==
* Docker
* https://docs.openfaas.com/cli/install/[OpenFaaS CLI]
* OpenFaaS: to try in localhost, maybe provision https://github.com/openfaas/faasd[faasd]

== Get OpenFaaS template ==

Get the Babashka OpenFaaS template:
[source, bash]
----
faas-cli template pull https://github.com/ccfontes/faas-bb
----

== Environment variables

[source, bash]
----
export DOCKER_REGISTRY_IMG_ORG_PATH=<registry org path>
----
Check link:stack.yml[stack.yml] to find out how `DOCKER_REGISTRY_IMG_ORG_PATH` is used.

== Building and deploying your function ==

To build and deploy the Functions to OpenFaaS, run the following command:
[source, bash]
----
faas-cli up
----

== Testing a function ==

Test a Function using the OpenFaaS UI or with the following command:
[source, bash]
----
echo "world" | faas-cli invoke bb-http-hello
----
Should ouput `"Hello, world"` string to the terminal.
