version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  bb-hello:
    lang: bb
    handler: ./bb-hello
    image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/bb-hello
  bb-lib:
    lang: bb
    handler: ./bb-lib
    image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/bb-lib
