name: Doc links

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Asciidoc-link-checker
        run: npm install -g asciidoc-link-check
      - name: Run asciidoc-link-check
        run: |
          git clone https://github.com/${{ github.repository_owner }}/faas-bb.git
          cd faas-bb
          git checkout ${{ github.head_ref || github.ref_name }}
          find . -name '*.adoc' -exec sh -c 'asciidoc-link-check -p "{}" || echo "error"' \; | grep -q "error" && exit 1 || exit 0
