name: clj-kondo
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.adoc"
  pull_request:
    paths-ignore:
      - "*.adoc"

jobs:
  clj-kondo:
    name: clj-kondo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: nnichols/clojure-lint-action@v2
      with:
        pattern: "*.clj"
        fail_on_error: true
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
