name: Unit tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo in current branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref || github.ref_name }}
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Babashka
      run: bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
    - name: Run unit tests
      run: bb tests.clj
      working-directory: ${{ github.workspace }}/template/bb
